import '../../firebase_options.dart';

const _placeholder = 'REPLACE_ME';

/// True once real Firebase credentials have been installed — i.e.
/// `flutterfire configure` has been run from `apps/mobile/` and it
/// overwrote `firebase_options.dart` with real values. False while the
/// `REPLACE_ME` placeholders generated by this project's scaffolding are
/// still present.
///
/// Checking `android.apiKey` directly (not `currentPlatform`) is
/// deliberate: `currentPlatform` throws on web/unsupported platforms
/// regardless of whether real credentials are present, so it can't be
/// used to detect "configured vs. not" — only the plain static fields
/// can be read safely on every platform.
bool get isFirebaseConfigured => DefaultFirebaseOptions.android.apiKey != _placeholder;

/// True while running without real Firebase credentials. In this mode:
///  - `main.dart` skips `Firebase.initializeApp()` entirely.
///  - `AuthController` uses a local mock session instead of Firebase
///    phone-OTP sign-in (see auth_controller.dart).
///
/// This is fully automatic — nothing to toggle by hand. Once
/// `flutterfire configure` overwrites `firebase_options.dart` with real
/// values, this flips to `false` and the app goes back to using real
/// Firebase everywhere, with no code changes required. See
/// AI_HANDOVER.md → "Development Mode" for the full explanation.
bool get isDevelopmentMode => !isFirebaseConfigured;
